import { CreditCard, SendToBack, Truck } from "lucide-react"


import { Facebook, Instagram, Linkedin, Twitter } from "lucide-react"

export const sociaMedia = [
    {
        id: 1,
        icon: Twitter,
    },
    {
        id: 2,
        icon: Instagram,
    },
    {
        id: 3,
        icon: Facebook,
    },
    {
        id: 4,
        icon: Linkedin,
    },
]

export const shippingData = [
    {
        id: 1,
        header: "Free Shipping",
        subHeader: "Over $29.00",
        icon: Truck,
    },
    {
        id: 2,
        header: "Secure Payments",
        subHeader: "With 5+ Payment options",
        icon: CreditCard,
    },
    {
        id: 3,
        header: "30 Days free return",
        subHeader: "No questions asked",
        icon: SendToBack,
    },
]

export const products = [
    {
        name: "Apple iPhone 16 Pro Max",
        description: "Flagship smartphone with 6.7-inch Super Retina XDR display and A17 Pro chip.",
        price: 1199.99,
        imageUrl: "/electronics/iphone16_pro_max.webp", 
        type: "electronics",
    },
    {
        name: "Samsung Galaxy S25 Ultra",
        description: "Premium Android smartphone with 200MP camera and Snapdragon 8 Gen 3.",
        price: 1299.99,
        imageUrl: "/electronics/samsung_s25_ultra.avif",
        type: "electronics",
    },
    {
        name: "Sony WH-1000XM5 Headphones",
        description: "Industry-leading noise-canceling wireless headphones with 30-hour battery life.",
        price: 349.99,
        imageUrl: "/electronics/sony_wh1000xm5.jpg",
        type: "electronics",
    },
    {
        name: "LG 65-inch OLED C3 Smart TV",
        description: "4K OLED TV with Dolby Vision, NVIDIA G-SYNC, and AI-powered picture enhancement.",
        price: 1799.99,
        imageUrl: "/electronics/lg_oled_c3_65.jpg",
        type: "electronics",
    },
    {
        name: "Razer BlackWidow V4 Pro Keyboard",
        description: "RGB mechanical gaming keyboard with customizable macros and green switches.",
        price: 229.99,
        imageUrl: "/electronics/razer_blackwidow_v4pro.webp",
        type: "electronics",
    },
    {
        name: "Apple MacBook Air M3 (13-inch)",
        description: "Thin and light laptop with Apple's M3 chip for performance and battery life.",
        price: 1099.00,
        imageUrl: "/electronics/macbook_air_m3.jpg",
        type: "electronics",
    },
    {
        name: "Dell XPS 13 Laptop",
        description: "Premium Windows ultrabook with InfinityEdge display and Intel Core Ultra.",
        price: 1299.00,
        imageUrl: "/electronics/dell_xps13.jpg",
        type: "electronics",
    },
    {
        name: "Apple iPad Air (M2)",
        description: "Powerful and versatile tablet with Liquid Retina display and M2 chip.",
        price: 599.00,
        imageUrl: "/electronics/ipad_air_m2.jpg",
        type: "electronics",
    },
    {
        name: "Sony PlayStation 5 Console",
        description: "Next-generation gaming console with fast SSD, DualSense controller, and 4K gaming.",
        price: 499.99,
        imageUrl: "/electronics/ps5_console.jpg",
        type: "electronics",
    },
    {
        name: "Microsoft Xbox Series X Console",
        description: "Most powerful Xbox console delivering 4K gaming and fast load times.",
        price: 499.99,
        imageUrl: "/electronics/xbox_series_x.jpg",
        type: "electronics",
    },
    {
        name: "Nintendo Switch - OLED Model",
        description: "Versatile hybrid gaming console with vibrant 7-inch OLED screen.",
        price: 349.99,
        imageUrl: "/electronics/nintendo_switch_oled.jpg",
        type: "electronics",
    },
    {
        name: "Amazon Echo Dot (5th Gen)",
        description: "Popular smart speaker with Alexa, improved audio, and smart home control.",
        price: 49.99,
        imageUrl: "/electronics/echo_dot_5thgen.jpg",
        type: "electronics",
    },
    {
        name: "Google Nest Hub (2nd Gen)",
        description: "Smart display with Google Assistant, sleep sensing, and entertainment features.",
        price: 99.99,
        imageUrl: "/electronics/google_nest_hub_2ndgen.jpg",
        type: "electronics",
    },
    {
        name: "Canon EOS R6 Mark II Camera",
        description: "Full-frame mirrorless camera for advanced photo and video performance.",
        price: 2499.00,
        imageUrl: "/electronics/canon_eos_r6_mkii.jpg",
        type: "electronics",
    },
    {
        name: "GoPro HERO12 Black Action Camera",
        description: "Rugged waterproof action camera with 5.3K video and HyperSmooth stabilization.",
        price: 399.99,
        imageUrl: "/electronics/gopro_hero12.jpg",
        type: "electronics",
    },
    {
        name: "Apple AirPods Pro (2nd generation)",
        description: "Wireless earbuds with active noise cancellation, transparency mode, and spatial audio.",
        price: 249.00,
        imageUrl: "/electronics/airpods_pro_2ndgen.jpg",
        type: "electronics",
    },
    {
        name: "Bose QuietComfort Ultra Earbuds",
        description: "Premium noise-cancelling earbuds with immersive audio.",
        price: 299.00,
        imageUrl: "/electronics/bose_qc_ultra_earbuds.jpg",
        type: "electronics",
    },
    {
        name: "Samsung 65-inch QN90C Neo QLED 4K TV",
        description: "High-end 4K TV with Mini LED technology for bright picture and contrast.",
        price: 1599.99,
        imageUrl: "/electronics/samsung_qn90c_65.jpg",
        type: "electronics",
    },
    {
        name: "Sonos One (Gen 2) Smart Speaker",
        description: "Compact smart speaker with rich sound, voice control (Alexa/Google Assistant).",
        price: 219.00,
        imageUrl: "/electronics/sonos_one_gen2.jpg",
        type: "electronics",
    },
    {
        name: "Logitech C920x HD Pro Webcam",
        description: "Popular webcam for streaming and video calls with Full HD 1080p quality.",
        price: 69.99,
        imageUrl: "/electronics/logitech_c920x.jpg",
        type: "electronics",
    },
    {
        name: "Nike Air Force 1 '07",
        description: "Classic low-top sneakers with crisp leather and timeless design.",
        price: 110.00, 
        imageUrl: "/clothing/nike_air_force_1_07.jpg", 
        type: "clothing",
    },
    {
        name: "Adidas Ultraboost Light",
        description: "Lightweight high-performance running shoes with responsive Boost cushioning.",
        price: 190.00, 
        imageUrl: "/clothing/adidas_ultraboost_light.webp",
        type: "clothing",
    },
    {
        name: "Levi’s 501 Original Fit Jeans",
        description: "Iconic straight-fit button-fly denim jeans, a timeless wardrobe staple.",
        price: 79.50,
        imageUrl: "/clothing/levis_501_original.jpg", 
        type: "clothing",
    },
    {
        name: "The North Face 1996 Retro Nuptse Jacket",
        description: "Warm, boxy, insulated down jacket with a retro look for winter.",
        price: 320.00,
        imageUrl: "/clothing/north_face_nuptse_1996.jpg", 
        type: "clothing",
    },
    {
        name: "Lululemon Align High-Rise Pant 25\"",
        description: "Buttery-soft leggings designed for yoga and everyday comfort.",
        price: 98.00,
        imageUrl: "/clothing/lululemon_align_pant.jpg", 
        type: "clothing",
    },
    {
        name: "H&M Regular Fit Crew-neck T-shirt (5-pack)",
        description: "Value pack of basic cotton crew-neck t-shirts for everyday wear.",
        price: 34.99,
        imageUrl: "/clothing/hm_tshirt_pack.jpg",
        type: "clothing",
    },
    {
        name: "Zara Straight Leg Full Length Jeans",
        description: "Trendy high-waisted straight leg jeans from a popular fast-fashion brand.",
        price: 49.90,
        imageUrl: "/clothing/zara_straight_jeans.jpg",
        type: "clothing",
    },
    {
        name: "Uniqlo Ultra Light Down Jacket",
        description: "Packable and lightweight down jacket for warmth without bulk.",
        price: 79.90,
        imageUrl: "/clothing/uniqlo_ultralight_down.jpg",
        type: "clothing",
    },
    {
        name: "Dr. Martens 1460 Smooth Leather Lace Up Boots",
        description: "Iconic 8-eye leather boots known for durability and style.",
        price: 170.00,
        imageUrl: "/clothing/dr_martens_1460.jpg",
        type: "clothing",
    },
    {
        name: "Birkenstock Arizona Soft Footbed Sandal",
        description: "Classic two-strap sandal known for comfort and cork footbed.",
        price: 140.00,
        imageUrl: "/clothing/birkenstock_arizona_sfb.jpg",
        type: "clothing",
    },
    {
        name: "Calvin Klein Cotton Stretch Boxer Briefs (3-pack)",
        description: "Comfortable and supportive cotton boxer briefs with logo waistband.",
        price: 45.00,
        imageUrl: "/clothing/calvin_klein_boxers.jpg",
        type: "clothing",
    },
    {
        name: "Patagonia Better Sweater Quarter-Zip Fleece",
        description: "Versatile fleece pullover made with recycled materials.",
        price: 119.00,
        imageUrl: "/clothing/patagonia_better_sweater.jpg",
        type: "clothing",
    },
    {
        name: "Nike Dri-FIT Tempo Running Shorts",
        description: "Lightweight, sweat-wicking shorts popular for running and training.",
        price: 30.00,
        imageUrl: "/clothing/nike_tempo_shorts.jpg",
        type: "clothing",
    },
    {
        name: "Under Armour Rival Fleece Hoodie",
        description: "Comfortable and warm fleece hoodie for casual wear or workouts.",
        price: 55.00,
        imageUrl: "/clothing/under_armour_hoodie.jpg",
        type: "clothing",
    },
    {
        name: "Brooks Ghost 15 Running Shoes",
        description: "Popular neutral running shoes known for cushioning and smooth rides.",
        price: 140.00,
        imageUrl: "/clothing/brooks_ghost_15.jpg",
        type: "clothing",
    },
    {
        name: "Levi's Original Trucker Jacket",
        description: "Classic denim jacket, a versatile layering piece.",
        price: 98.00,
        imageUrl: "/clothing/levis_trucker_jacket.jpg",
        type: "clothing",
    },
    {
        name: "Gap Classic Crewneck Sweater",
        description: "Simple and versatile cotton crewneck sweater.",
        price: 49.95,
        imageUrl: "/clothing/gap_crewneck_sweater.jpg",
        type: "clothing",
    },
    {
        name: "J.Crew Ludlow Slim-fit Suit Jacket in Italian Wool",
        description: "Well-regarded suit jacket for professional or formal occasions.",
        price: 450.00, 
        imageUrl: "/clothing/jcrew_ludlow_jacket.jpg",
        type: "clothing",
    },
    {
        name: "Everlane The Cashmere Crew Sweater",
        description: "Soft and ethically sourced cashmere sweater.",
        price: 145.00,
        imageUrl: "/clothing/everlane_cashmere_crew.jpg",
        type: "clothing",
    },
    {
        name: "Bombas Original Ankle Socks",
        description: "Comfort-focused socks known for arch support and quality.",
        price: 13.00, 
        imageUrl: "/clothing/bombas_ankle_socks.jpg",
        type: "clothing",
    },
    {
        name: "Dyson V15 Detect Absolute Vacuum",
        description: "Top-tier cordless vacuum with laser dust detection and powerful suction.",
        price: 749.99,
        imageUrl: "/home/dyson_v15_detect.jpg", 
        type: "home_appliances",
    },
    {
        name: "Nespresso VertuoPlus Coffee and Espresso Maker by De'Longhi",
        description: "Automatic single-serve machine using versatile Vertuo capsules.",
        price: 169.00, 
        imageUrl: "/home/nespresso_vertuoplus_delonghi.jpg", 
        type: "home_appliances",
    },
    {
        name: "KitchenAid Artisan Series 5-Quart Tilt-Head Stand Mixer",
        description: "Iconic and versatile stand mixer for baking and cooking.",
        price: 449.99,
        imageUrl: "/home/kitchenaid_artisan_5qt.jpg", 
        type: "home_appliances",
    },
    {
        name: "Instant Pot Duo 7-in-1 Electric Pressure Cooker (6 Qt)",
        description: "Popular multi-cooker: pressure, slow, rice cooker, steamer, sauté, yogurt maker, warmer.",
        price: 89.99,
        imageUrl: "/home/instant_pot_duo_6qt.jpg", 
        type: "home_appliances",
    },
    {
        name: "COSORI Pro II Air Fryer Oven Combo (5.8QT)",
        description: "Large capacity air fryer with multiple presets and smart features.",
        price: 119.99,
        imageUrl: "/home/cosori_pro_ii_5_8qt.jpg", 
        type: "home_appliances",
    },
     {
        name: "Samsung Bespoke 4-Door Flex Refrigerator",
        description: "Customizable refrigerator with flexible storage options and modern design.",
        price: 2999.00,
        imageUrl: "/home/samsung_bespoke_fridge.jpg",
        type: "home_appliances",
    },
    {
        name: "LG WashTower Electric Stacked Laundry Center",
        description: "Space-saving washer and dryer unit with AI technology and center control panel.",
        price: 2199.00,
        imageUrl: "/home/lg_washtower.jpg",
        type: "home_appliances",
    },
    {
        name: "Bosch 300 Series Dishwasher",
        description: "Quiet and reliable dishwasher known for cleaning performance.",
        price: 849.00,
        imageUrl: "/home/bosch_300_dishwasher.jpg",
        type: "home_appliances",
    },
    {
        name: "iRobot Roomba j7+ Self-Emptying Robot Vacuum",
        description: "Smart robot vacuum with obstacle avoidance and automatic dirt disposal.",
        price: 799.00,
        imageUrl: "/home/irobot_roomba_j7plus.jpg",
        type: "home_appliances",
    },
    {
        name: "Shark NV360 Navigator Lift-Away Deluxe Upright Vacuum",
        description: "Popular upright vacuum with detachable pod for portable cleaning.",
        price: 199.99,
        imageUrl: "/home/shark_navigator_nv360.jpg",
        type: "home_appliances",
    },
     {
        name: "Breville Barista Express Espresso Machine",
        description: "Semi-automatic espresso machine with integrated grinder for home baristas.",
        price: 749.95,
        imageUrl: "/home/breville_barista_express.jpg",
        type: "home_appliances",
    },
    {
        name: "Cuisinart Custom 14-Cup Food Processor",
        description: "Large capacity food processor for chopping, slicing, shredding, and mixing.",
        price: 249.95,
        imageUrl: "/home/cuisinart_14cup_foodprocessor.jpg",
        type: "home_appliances",
    },
    {
        name: "Ninja Professional Plus Blender with Auto-iQ",
        description: "Powerful blender for smoothies, ice crushing, and food processing.",
        price: 119.99,
        imageUrl: "/home/ninja_professional_blender.jpg",
        type: "home_appliances",
    },
    {
        name: "Panasonic NN-SN67KS Microwave Oven (1.2 Cu. Ft.)",
        description: "Countertop microwave with inverter technology for even cooking.",
        price: 199.95,
        imageUrl: "/home/panasonic_microwave_1_2cuft.jpg",
        type: "home_appliances",
    },
    {
        name: "BLACK+DECKER 4-Slice Toaster Oven",
        description: "Compact countertop oven for toasting, baking, and broiling.",
        price: 49.99,
        imageUrl: "/home/blackdecker_toaster_oven.jpg",
        type: "home_appliances",
    },
    {
        name: "Rowenta DW5080 Focus Steam Iron",
        description: "High-performance steam iron with stainless steel soleplate.",
        price: 99.00,
        imageUrl: "/home/rowenta_dw5080_iron.jpg",
        type: "home_appliances",
    },
    {
        name: "Levoit Core 300 True HEPA Air Purifier",
        description: "Popular air purifier for small to medium rooms, effective against dust and allergens.",
        price: 99.99,
        imageUrl: "/home/levoit_core300_airpurifier.jpg",
        type: "home_appliances",
    },
    {
        name: "Honeywell HT-900 TurboForce Air Circulator Fan",
        description: "Small but powerful fan for personal cooling.",
        price: 19.99,
        imageUrl: "/home/honeywell_turboforce_fan.jpg",
        type: "home_appliances",
    },
    {
        name: "Dyson Purifier Cool Formaldehyde TP09",
        description: "Premium air purifier and fan that also detects and destroys formaldehyde.",
        price: 749.99,
        imageUrl: "/home/dyson_purifier_cool_tp09.jpg",
        type: "home_appliances",
    },
    {
        name: "Keurig K-Elite Single-Serve K-Cup Pod Coffee Maker",
        description: "Versatile Keurig brewer with multiple cup sizes and iced coffee setting.",
        price: 189.99,
        imageUrl: "/home/keurig_k_elite.jpg",
        type: "home_appliances",
    },
    {
        name: "Atomic Habits by James Clear",
        description: "An easy & proven way to build good habits & break bad ones. Perennial bestseller.",
        price: 16.20,
        imageUrl: "/books/atomic_habits_clear.jpg", 
        type: "books",
    },
    {
        name: "The Seven Husbands of Evelyn Hugo by Taylor Jenkins Reid",
        description: "A gripping novel about a reclusive Hollywood icon revealing her life story.",
        price: 9.49,
        imageUrl: "/books/evelyn_hugo_reid.jpg", 
        type: "books",
    },
    {
        name: "Rich Dad Poor Dad by Robert T. Kiyosaki",
        description: "Classic personal finance book advocating financial literacy and independence.",
        price: 7.59,
        imageUrl: "/books/rich_dad_poor_dad_kiyosaki.jpg", 
        type: "books",
    },
    {
        name: "The Psychology of Money by Morgan Housel",
        description: "Timeless lessons on wealth, greed, and happiness through storytelling.",
        price: 13.55,
        imageUrl: "/books/psychology_of_money_housel.jpg", 
        type: "books",
    },
    {
        name: "Where the Crawdads Sing by Delia Owens",
        description: "A hugely popular coming-of-age story intertwined with a murder mystery.",
        price: 10.98,
        imageUrl: "/books/crawdads_sing_owens.jpg", 
        type: "books",
    },
    {
        name: "It Ends with Us by Colleen Hoover",
        description: "A bestselling romance novel exploring themes of love and abuse.",
        price: 10.39,
        imageUrl: "/books/it_ends_with_us_hoover.jpg",
        type: "books",
    },
    {
        name: "The Silent Patient by Alex Michaelides",
        description: "A shocking psychological thriller with a twisting plot.",
        price: 13.99,
        imageUrl: "/books/silent_patient_michaelides.jpg",
        type: "books",
    },
    {
        name: "Sapiens: A Brief History of Humankind by Yuval Noah Harari",
        description: "A sweeping exploration of human history and our species' impact.",
        price: 17.49,
        imageUrl: "/books/sapiens_harari.jpg",
        type: "books",
    },
    {
        name: "Educated: A Memoir by Tara Westover",
        description: "An inspiring memoir about overcoming a challenging upbringing to pursue education.",
        price: 14.99,
        imageUrl: "/books/educated_westover.jpg",
        type: "books",
    },
    {
        name: "Becoming by Michelle Obama",
        description: "The intimate and uplifting memoir of the former First Lady of the United States.",
        price: 11.89,
        imageUrl: "/books/becoming_obama.jpg",
        type: "books",
    },
    {
        name: "Dune by Frank Herbert",
        description: "Classic science fiction epic set on the desert planet Arrakis.",
        price: 9.99,
        imageUrl: "/books/dune_herbert.jpg",
        type: "books",
    },
    {
        name: "Pride and Prejudice by Jane Austen",
        description: "Beloved classic romance novel featuring Elizabeth Bennet and Mr. Darcy.",
        price: 7.99,
        imageUrl: "/books/pride_and_prejudice_austen.jpg",
        type: "books",
    },
    {
        name: "The Subtle Art of Not Giving a F*ck by Mark Manson",
        description: "A counterintuitive approach to living a good life, focusing on what truly matters.",
        price: 15.49,
        imageUrl: "/books/subtle_art_manson.jpg",
        type: "books",
    },
    {
        name: "Thinking, Fast and Slow by Daniel Kahneman",
        description: "Nobel laureate explores the two systems that drive the way we think.",
        price: 12.89,
        imageUrl: "/books/thinking_fast_slow_kahneman.jpg",
        type: "books",
    },
    {
        name: "To Kill a Mockingbird by Harper Lee",
        description: "A timeless American classic exploring justice, prejudice, and childhood innocence.",
        price: 8.99,
        imageUrl: "/books/mockingbird_lee.jpg",
        type: "books",
    },
    {
        name: "1984 by George Orwell",
        description: "Dystopian masterpiece warning against totalitarianism and surveillance.",
        price: 9.99,
        imageUrl: "/books/1984_orwell.jpg",
        type: "books",
    },
    {
        name: "The Lord of the Rings by J.R.R. Tolkien",
        description: "Epic high-fantasy novel, often considered one of the greatest books ever written.",
        price: 22.99,
        imageUrl: "/books/lotr_tolkien.jpg",
        type: "books",
    },
    {
        name: "Harry Potter and the Sorcerer's Stone by J.K. Rowling",
        description: "The first book in the incredibly popular fantasy series about a young wizard.",
        price: 8.99,
        imageUrl: "/books/harry_potter_1_rowling.jpg",
        type: "books",
    },
    {
        name: "Magnolia Table, Vol. 3 by Joanna Gaines",
        description: "Popular cookbook featuring recipes for home-style comfort food.",
        price: 24.99,
        imageUrl: "/books/magnolia_table_3_gaines.jpg",
        type: "books",
    },
    {
        name: "Goodnight Moon by Margaret Wise Brown",
        description: "Classic children's board book, a staple for bedtime reading.",
        price: 6.99,
        imageUrl: "/books/goodnight_moon_brown.jpg",
        type: "books",
    },
    {
        name: "Apple Watch Series 9 (GPS, 41mm)",
        description: "Leading smartwatch with health tracking, connectivity, and Always-On display.",
        price: 399.00,
        imageUrl: "/accessories/apple_watch_s9_41mm.jpg", 
        type: "accessories",
    },
    {
        name: "Ray-Ban Classic Wayfarer Sunglasses (RB2140)",
        description: "Iconic unisex sunglasses model offering timeless style and UV protection.",
        price: 163.00,
        imageUrl: "/accessories/rayban_wayfarer_rb2140.jpg", 
        type: "accessories",
    },
    {
        name: "Hydro Flask Standard Mouth Bottle (24 oz)",
        description: "Popular insulated stainless steel water bottle keeping drinks cold or hot.",
        price: 39.95,
        imageUrl: "/accessories/hydro_flask_24oz.jpg", 
        type: "accessories",
    },
    {
        name: "Anker PowerCore 10000 Portable Charger",
        description: "Compact and reliable high-speed charging power bank for mobile devices.",
        price: 21.99,
        imageUrl: "/accessories/anker_powercore_10k.jpg", 
        type: "accessories",
    },
    {
        name: "Fjällräven Kånken Classic Backpack",
        description: "Durable and iconic Scandinavian design backpack for everyday use.",
        price: 79.95,
        imageUrl: "/accessories/fjallraven_kanken_classic.jpg", 
        type: "accessories",
    },
    {
        name: "Fossil Men's Derrick RFID-Blocking Leather Bifold Wallet",
        description: "Classic leather wallet with RFID protection for security.",
        price: 50.00,
        imageUrl: "/accessories/fossil_derrick_wallet.jpg",
        type: "accessories",
    },
     {
        name: "Michael Kors Jet Set Large Crossgrain Leather Tote Bag",
        description: "Popular designer tote bag known for its style and functionality.",
        price: 198.00,
        imageUrl: "/accessories/mk_jetset_tote.jpg",
        type: "accessories",
    },
    {
        name: "Pandora Moments Snake Chain Charm Bracelet",
        description: "Customizable sterling silver charm bracelet, a popular gift item.",
        price: 65.00,
        imageUrl: "/accessories/pandora_moments_bracelet.jpg",
        type: "accessories",
    },
    {
        name: "Swatch Gent Standard Watch (Various Styles)",
        description: "Affordable and stylish Swiss-made watches in numerous designs.",
        price: 85.00,
        imageUrl: "/accessories/swatch_gent_watch.jpg",
        type: "accessories",
    },
    {
        name: "Coach Signature Buckle Reversible Leather Belt",
        description: "Designer leather belt, often reversible for versatility.",
        price: 150.00,
        imageUrl: "/accessories/coach_signature_belt.jpg",
        type: "accessories",
    },
    {
        name: "The Tie Bar Solid Silk Tie (Various Colors)",
        description: "Affordable yet quality silk ties for formal or business wear.",
        price: 28.00,
        imageUrl: "/accessories/tiebar_silk_tie.jpg",
        type: "accessories",
    },
    {
        name: "Away The Carry-On Suitcase",
        description: "Popular hard-shell carry-on luggage known for design and durability.",
        price: 275.00,
        imageUrl: "/accessories/away_carryon.jpg",
        type: "accessories",
    },
    {
        name: "Apple MagSafe Charger",
        description: "Magnetic wireless charger designed for iPhone 12 and later models.",
        price: 39.00,
        imageUrl: "/accessories/apple_magsafe_charger.jpg",
        type: "accessories",
    },
    {
        name: "OtterBox Defender Series Phone Case (Model Specific)",
        description: "Highly protective phone case known for ruggedness.",
        price: 59.95, // Price varies by phone model
        imageUrl: "/accessories/otterbox_defender_case.jpg",
        type: "accessories",
    },
    {
        name: "Beats Fit Pro True Wireless Noise Cancelling Earbuds",
        description: "Secure-fit wireless earbuds with noise cancellation, great for workouts.",
        price: 199.95,
        imageUrl: "/accessories/beats_fit_pro.jpg",
        type: "accessories",
    },
    {
        name: "Garmin Forerunner 255 Music GPS Running Watch",
        description: "Advanced GPS watch for runners with music storage and training features.",
        price: 399.99,
        imageUrl: "/accessories/garmin_forerunner_255m.jpg",
        type: "accessories",
    },
    {
        name: "Carhartt Acrylic Watch Hat A18",
        description: "Iconic and durable beanie hat, popular for workwear and casual style.",
        price: 19.99,
        imageUrl: "/accessories/carhartt_watch_hat.jpg",
        type: "accessories",
    },
    {
        name: "Kate Spade New York Mini Pendant Necklace",
        description: "Simple and elegant designer pendant necklace, often gifted.",
        price: 58.00,
        imageUrl: "/accessories/katespade_mini_pendant.jpg",
        type: "accessories",
    },
    {
        name: "Yeti Rambler 20 oz Tumbler with MagSlider Lid",
        description: "Durable insulated tumbler keeping drinks hot or cold for hours.",
        price: 35.00,
        imageUrl: "/accessories/yeti_rambler_20oz.jpg",
        type: "accessories",
    },
    {
        name: "Herschel Supply Co. Novel Duffel Bag",
        description: "Stylish duffel bag with signature shoe compartment.",
        price: 99.99,
        imageUrl: "/accessories/herschel_novel_duffel.jpg",
        type: "accessories",
    },
    {
        name: "Optimum Nutrition Gold Standard 100% Whey Protein (5 lbs)",
        description: "Leading whey protein powder for muscle building and recovery.",
        price: 89.99, 
        imageUrl: "/supplements/on_gold_standard_whey_5lb.jpg", 
        type: "supplements",
    },
    {
        name: "Nature Made Vitamin D3 2000 IU (50 mcg) Softgels",
        description: "Essential vitamin D supplement supporting bone, immune, and muscle health.",
        price: 15.99, 
        imageUrl: "/supplements/nature_made_d3_2000iu.jpg", 
        type: "supplements",
    },
    {
        name: "NOW Foods Creatine Monohydrate Powder (Micronized, 500g)",
        description: "Pure micronized creatine monohydrate supporting muscle strength and power.",
        price: 24.99, 
        imageUrl: "/supplements/now_creatine_500g.jpg", 
        type: "supplements",
    },
    {
        name: "Nordic Naturals Ultimate Omega Softgels",
        description: "High-potency EPA & DHA fish oil supplement for brain and heart health.",
        price: 29.95,
        imageUrl: "/supplements/nordic_naturals_ultimate_omega.jpg", 
        type: "supplements",
    },
    {
        name: "Garden of Life Vitamin Code Raw One Multivitamin for Women/Men",
        description: "Whole food multivitamin derived from raw fruits and vegetables.",
        price: 35.99, 
        imageUrl: "/supplements/gardenoflife_vitamin_code_raw.jpg", 
        type: "supplements",
    },
    {
        name: "Vital Proteins Collagen Peptides Powder (Unflavored, 20 oz)",
        description: "Popular collagen supplement supporting hair, skin, nail, and joint health.",
        price: 47.00,
        imageUrl: "/supplements/vital_proteins_collagen_20oz.jpg",
        type: "supplements",
    },
    {
        name: "Culturelle Daily Probiotic Capsules (Digestive Health)",
        description: "Probiotic supplement with Lactobacillus rhamnosus GG for digestive balance.",
        price: 19.99,
        imageUrl: "/supplements/culturelle_daily_probiotic.jpg",
        type: "supplements",
    },
    {
        name: "Nature's Bounty Vitamin C Gummies (250mg)",
        description: "Tasty gummy vitamin C supplement for immune support.",
        price: 12.99, 
        imageUrl: "/supplements/natures_bounty_vitc_gummies.jpg",
        type: "supplements",
    },
    {
        name: "NOW Foods Magnesium Citrate Capsules (400 mg)",
        description: "Highly absorbable magnesium supplement for nerve and muscle function.",
        price: 17.99, 
        imageUrl: "/supplements/now_magnesium_citrate_400mg.jpg",
        type: "supplements",
    },
    {
        name: "Vega Protein & Greens Plant-Based Protein Powder",
        description: "Vegan protein powder made from pea protein with added greens.",
        price: 39.99,
        imageUrl: "/supplements/vega_protein_greens.jpg",
        type: "supplements",
    },
    {
        name: "Carlson Labs The Very Finest Fish Oil (Liquid)",
        description: "Liquid fish oil supplement rich in EPA and DHA, often lemon flavored.",
        price: 34.90, 
        imageUrl: "/supplements/carlson_fish_oil_liquid.jpg",
        type: "supplements",
    },
    {
        name: "Goli Nutrition Apple Cider Vinegar Gummies",
        description: "Popular gummies providing benefits of apple cider vinegar without the taste.",
        price: 18.98, 
        imageUrl: "/supplements/goli_acv_gummies.jpg",
        type: "supplements",
    },
    {
        name: "Olly Sleep Melatonin Gummies",
        description: "Gummy supplement with melatonin, L-Theanine, and botanicals to support sleep.",
        price: 13.99, 
        imageUrl: "/supplements/olly_sleep_gummies.jpg",
        type: "supplements",
    },
    {
        name: "Thorne Basic B-Complex Capsules",
        description: "High-quality B-vitamin complex supporting energy production and neurological function.",
        price: 25.00, 
        imageUrl: "/supplements/thorne_basic_b_complex.jpg",
        type: "supplements",
    },
    {
        name: "Optimum Nutrition ZMA (Zinc Magnesium Aspartate)",
        description: "Supplement blend used by athletes to support muscle recovery and sleep quality.",
        price: 21.99,
        imageUrl: "/supplements/on_zma.jpg",
        type: "supplements",
    },
    {
        name: "Cellucor C4 Original Pre Workout Powder",
        description: "Popular pre-workout supplement for energy, focus, and endurance.",
        price: 29.99,
        imageUrl: "/supplements/cellucor_c4_original.jpg",
        type: "supplements",
    },
    {
        name: "Sports Research Vitamin K2 + D3 Supplement",
        description: "Combined supplement supporting bone and cardiovascular health.",
        price: 19.95,
        imageUrl: "/supplements/sports_research_k2d3.jpg",
        type: "supplements",
    },
    {
        name: "SmartyPants Kids Formula Daily Gummy Multivitamin",
        description: "Popular children's gummy multivitamin with omega-3s and vitamin D.",
        price: 20.99,
        imageUrl: "/supplements/smartypants_kids_gummies.jpg",
        type: "supplements",
    },
    {
        name: "Quest Nutrition Protein Bar (Various Flavors)",
        description: "High-protein, low-sugar snack bar popular for fitness enthusiasts.",
        price: 2.49,
        imageUrl: "/supplements/quest_protein_bar.jpg",
        type: "supplements",
    },
    {
        name: "Orgain Organic Plant Based Protein Powder",
        description: "Another popular organic vegan protein powder option.",
        price: 29.99,
        imageUrl: "/supplements/orgain_plant_protein.jpg",
        type: "supplements",
    },
];

export const productData = [
    {
      id: 1,
      name: "Minimal Watch",
      description:
        "Elevate your style with the sophisticated Lryx Watch, a perfect blend of elegance and functionality",
      price: "349.99",
      category: "GEAR",
      image: "minimal-watch.avif",
    },
    {
        id: 2,
      name: "Watch Screen Protector",
      description:
        "Stay connected and monitor your fitness effortlessly with the Watch SE 3, your essential companion for an active lifestyle",
      price: "349.99",
      category: "GEAR",
      image: "screen-protector.avif",
    },
    {
        id: 3,
      name: "Hash ANC Headphone",
      description:
        "Experience deep, powerful bass and crystal-clear audio with the Headphone 21 Bass, perfect for music enthusiasts",
      price: "499.99",
      category: "GEAR",
      image: "headphones.avif",
    },
    {
        id: 4,
      name: "Buds 2 Wireless",
      description:
        "Immerse yourself in premium sound quality and enjoy the ultimate listening experience with our top-notch earbuds",
      price: "389.99",
      category: "GEAR",
      image: "airbuds.avif",
    },
  ];
