export const products = [
    // Electronics
    {
        name: "Apple iPhone 16 Pro Max",
        description: "Flagship smartphone with 6.7-inch Super Retina XDR display and A17 Pro chip.",
        price: 1199.99,
        imageUrl: "/electronics/iphone.webp",
        type: "electronics",
    },
    {
        name: "Samsung Galaxy S25 Ultra",
        description: "Premium Android smartphone with 200MP camera and Snapdragon 8 Gen 3.",
        price: 1299.99,
        imageUrl: "/electronics/s25-ultra.avif",
        type: "electronics",
    },
    {
        name: "Sony WH-1000XM5 Headphones",
        description: "Industry-leading noise-canceling wireless headphones with 30-hour battery life.",
        price: 349.99,
        imageUrl: "/electronics/sony-headphones.jpg",
        type: "electronics",
    },
    {
        name: "LG 65-inch OLED C3 Smart TV",
        description: "4K OLED TV with Dolby Vision, NVIDIA G-SYNC, and AI-powered picture enhancement.",
        price: 1799.99,
        imageUrl: "/electronics/lg.jpg",
        type: "electronics",
    },
    {
        name: "Razer BlackWidow V4 Pro Keyboard",
        description: "RGB mechanical gaming keyboard with customizable macros and green switches.",
        price: 229.99,
        imageUrl: "/electronics/razer.webp",
        type: "electronics",
    },

    // // Clothing
    // {
    //     name: "Nike Air Force 1",
    //     description: "Classic low-top sneakers with premium leather and timeless design.",
    //     price: 109.99,
    //     imageUrl: "/clothing/nike_air_force_1.jpg",
    //     type: "clothing",
    // },
    // {
    //     name: "Adidas Ultraboost 22",
    //     description: "High-performance running shoes with responsive Boost cushioning.",
    //     price: 179.99,
    //     imageUrl: "/clothing/adidas_ultraboost_22.jpg",
    //     type: "clothing",
    // },
    // {
    //     name: "Levi’s 511 Slim Fit Jeans",
    //     description: "Stretch denim slim-fit jeans with a classic look.",
    //     price: 69.99,
    //     imageUrl: "/clothing/levis_511_jeans.jpg",
    //     type: "clothing",
    // },
    // {
    //     name: "The North Face Nuptse Jacket",
    //     description: "Warm, insulated down jacket for winter adventures.",
    //     price: 279.99,
    //     imageUrl: "/clothing/north_face_nuptse.jpg",
    //     type: "clothing",
    // },
    // {
    //     name: "Polo Ralph Lauren Classic Fit T-Shirt",
    //     description: "Premium cotton t-shirt with the iconic Polo logo.",
    //     price: 45.99,
    //     imageUrl: "/clothing/polo_ralph_lauren_tshirt.jpg",
    //     type: "clothing",
    // },

    // // Home Appliances
    // {
    //     name: "Dyson V15 Detect Vacuum Cleaner",
    //     description: "Cordless vacuum with laser dust detection and powerful suction.",
    //     price: 699.99,
    //     imageUrl: "/home/dyson_v15.jpg",
    //     type: "home_appliances",
    // },
    // {
    //     name: "Nespresso Vertuo Plus Coffee Maker",
    //     description: "Automatic espresso and coffee machine with capsule-based brewing.",
    //     price: 149.99,
    //     imageUrl: "/home/nespresso_vertuo.jpg",
    //     type: "home_appliances",
    // },
    // {
    //     name: "KitchenAid Artisan Stand Mixer",
    //     description: "5-quart tilt-head stand mixer for baking and cooking needs.",
    //     price: 429.99,
    //     imageUrl: "/home/kitchenaid_artisan.jpg",
    //     type: "home_appliances",
    // },
    // {
    //     name: "Instant Pot Duo 7-in-1",
    //     description: "Multi-functional electric pressure cooker for quick and easy meals.",
    //     price: 99.99,
    //     imageUrl: "/home/instant_pot_duo.jpg",
    //     type: "home_appliances",
    // },
    // {
    //     name: "Philips Air Fryer XXL",
    //     description: "Oil-less fryer with rapid air technology for healthier cooking.",
    //     price: 279.99,
    //     imageUrl: "/home/philips_air_fryer.jpg",
    //     type: "home_appliances",
    // },

    // // Books
    // {
    //     name: "Atomic Habits by James Clear",
    //     description: "Bestseller on building good habits and breaking bad ones.",
    //     price: 18.99,
    //     imageUrl: "/books/atomic_habits.jpg",
    //     type: "books",
    // },
    // {
    //     name: "The Lean Startup by Eric Ries",
    //     description: "Essential guide for building and scaling startups using lean principles.",
    //     price: 22.99,
    //     imageUrl: "/books/the_lean_startup.jpg",
    //     type: "books",
    // },
    // {
    //     name: "Rich Dad Poor Dad by Robert Kiyosaki",
    //     description: "Personal finance book about achieving financial freedom.",
    //     price: 16.99,
    //     imageUrl: "/books/rich_dad_poor_dad.jpg",
    //     type: "books",
    // },
    // {
    //     name: "The Psychology of Money by Morgan Housel",
    //     description: "Timeless lessons on wealth, greed, and happiness.",
    //     price: 21.99,
    //     imageUrl: "/books/psychology_of_money.jpg",
    //     type: "books",
    // },
    // {
    //     name: "Deep Work by Cal Newport",
    //     description: "A guide to mastering focused work in a distracted world.",
    //     price: 20.99,
    //     imageUrl: "/books/deep_work.jpg",
    //     type: "books",
    // },

    // // Accessories
    // {
    //     name: "Rolex Submariner",
    //     description: "Luxury stainless steel dive watch with automatic movement.",
    //     price: 9999.99,
    //     imageUrl: "/accessories/rolex_submariner.jpg",
    //     type: "accessories",
    // },
    // {
    //     name: "Apple Watch Series 9",
    //     description: "Smartwatch with Always-On Retina display and fitness tracking.",
    //     price: 399.99,
    //     imageUrl: "/accessories/apple_watch_series_9.jpg",
    //     type: "accessories",
    // },
    // {
    //     name: "Gucci GG Marmont Leather Wallet",
    //     description: "Elegant leather wallet with the iconic GG logo.",
    //     price: 499.99,
    //     imageUrl: "/accessories/gucci_wallet.jpg",
    //     type: "accessories",
    // },
    // {
    //     name: "Ray-Ban Wayfarer Sunglasses",
    //     description: "Classic UV-protected sunglasses with polarized lenses.",
    //     price: 154.99,
    //     imageUrl: "/accessories/rayban_wayfarer.jpg",
    //     type: "accessories",
    // },
    // {
    //     name: "Herschel Little America Backpack",
    //     description: "Durable travel backpack with padded laptop sleeve.",
    //     price: 109.99,
    //     imageUrl: "/accessories/herschel_backpack.jpg",
    //     type: "accessories",
    // },
];
