import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
<<<<<<< HEAD

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
=======
import { Providers } from "./provider";
import Navbar from "~/components/Navbar";

export const metadata: Metadata = {
  title: "Tech Wave",
  description: "This is an ecommerce website built with Next.js and Tailwind CSS",
>>>>>>> 44b7e5e (working on auth)
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
<<<<<<< HEAD
        <TRPCReactProvider>{children}</TRPCReactProvider>
=======
        <Providers>
        <TRPCReactProvider>
          <Navbar />
          {children}
        </TRPCReactProvider>
        </Providers>
>>>>>>> 44b7e5e (working on auth)
      </body>
    </html>
  );
}
